export interface ItemContext {
  id: number | string;
  url: string;
  title: string;
}

export interface DealContext {
  id: number | string;
  listingUrl: string;
  title: string;
  priceAmount?: number | null;
  originalPriceAmount?: number | null;
  priceCurrency?: string | null;
  priceDropText?: string | null;
  publishedAt?: string | null;
  daysOnMarket?: number | null;
}

export interface RenderContext {
  items?: ItemContext[];
  deals?: DealContext[];
  bot?: string;
  episodeId?: number | string;
}

/**
 * Sanitises untrusted text from feeds, external APIs, and user inputs.
 * Strips script/style tags and standard HTML markup, decodes entities,
 * removes control characters, collapses whitespace, truncates to maxLen,
 * and escapes '<' and '>' to prevent prompt breakout.
 */
export function sanitiseUntrusted(text: string, maxLen = 500): string {
  if (!text || typeof text !== 'string') return '';

  let clean = text
    .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '') // Strip script tags completely
    .replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi, '')   // Strip style tags completely
    .replace(/<\/?(html|body|head|b|i|u|strong|em|p|a|div|span|h[1-6]|ul|ol|li|br|hr|img|table|tr|td|th)\b[^>]*>/gi, ' ') // Strip standard HTML elements
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '') // Remove non-printable control characters
    .replace(/\s+/g, ' ') // Collapse whitespace
    .trim();

  if (clean.length > maxLen) {
    clean = clean.slice(0, maxLen).trim();
  }

  // Escape XML-like delimiter chars so data cannot close our wrapper tags
  clean = clean.replace(/</g, '&lt;').replace(/>/g, '&gt;');

  return clean;
}

/**
 * Replaces [[item:ID]] and [[deal:ID]] tokens with clean rendered links
 * ONLY if the ID was provided in the allowed context.
 * Strips unknown [[...]] tokens and unauthorized raw URLs.
 */
export function renderTokens(text: string, context: RenderContext): string {
  if (!text) return '';

  const itemMap = new Map<string, ItemContext>();
  if (context.items) {
    for (const item of context.items) {
      itemMap.set(String(item.id), item);
    }
  }

  const dealMap = new Map<string, DealContext>();
  if (context.deals) {
    for (const deal of context.deals) {
      dealMap.set(String(deal.id), deal);
    }
  }

  // Replace [[item:ID]] tokens
  let rendered = text.replace(/\[\[item:(\d+)\]\]/gi, (match, id) => {
    const item = itemMap.get(String(id));
    if (item) {
      const outUrl = `/api/out?u=${encodeURIComponent(item.url)}&type=item&id=${encodeURIComponent(id)}`;
      return `[${item.title || `Source #${id}`}](${outUrl})`;
    }
    return ''; // Remove if ID is not in context
  });

  // Replace [[deal:ID]] tokens
  rendered = rendered.replace(/\[\[deal:(\d+)\]\]/gi, (match, id) => {
    const deal = dealMap.get(String(id));
    if (deal) {
      const bot = context.bot ? `&b=${encodeURIComponent(context.bot)}` : '';
      const ep = context.episodeId ? `&e=${encodeURIComponent(context.episodeId)}` : '';
      const outUrl = `/api/out?u=${encodeURIComponent(deal.listingUrl)}&type=deal&id=${encodeURIComponent(id)}${bot}${ep}`;
      
      let priceText = '';
      const curr = deal.priceCurrency || '$';
      if (deal.priceAmount) {
        priceText = ` (${curr}${deal.priceAmount}`;
        if (deal.originalPriceAmount && deal.originalPriceAmount > deal.priceAmount) {
          priceText += ` · was ${curr}${deal.originalPriceAmount}`;
        }
        if (deal.daysOnMarket !== undefined && deal.daysOnMarket !== null) {
          priceText += ` · ${deal.daysOnMarket}d on Reverb`;
        }
        priceText += `)`;
      } else if (deal.daysOnMarket !== undefined && deal.daysOnMarket !== null) {
        priceText = ` (${deal.daysOnMarket}d on Reverb)`;
      }

      return `[${deal.title || 'Reverb Deal'}${priceText}](${outUrl})`;
    }
    return ''; // Remove if deal ID not in context
  });

  // Strip any remaining unrecognised [[...]] tokens
  rendered = rendered.replace(/\[\[[^\]]+\]\]/g, '');

  // Strip any raw unapproved http(s) URLs generated by the model
  rendered = rendered.replace(/\bhttps?:\/\/[^\s<>)"]+/gi, (rawUrl) => {
    // If it's already an internal /api/out link, allow it
    if (rawUrl.startsWith('/api/out') || rawUrl.includes('/api/out')) {
      return rawUrl;
    }
    return '';
  });

  return rendered.trim();
}

/**
 * Validates user input length and content
 */
export function validateUserInput(input: string, maxChars = 500): { valid: boolean; error?: string; sanitised: string } {
  if (!input || typeof input !== 'string') {
    return { valid: false, error: 'Message cannot be empty.', sanitised: '' };
  }

  const trimmed = input.trim();
  if (trimmed.length === 0) {
    return { valid: false, error: 'Message cannot be blank.', sanitised: '' };
  }

  if (trimmed.length > maxChars) {
    return { valid: false, error: `Message exceeds limit of ${maxChars} characters.`, sanitised: '' };
  }

  const sanitised = sanitiseUntrusted(trimmed, maxChars);
  return { valid: true, sanitised };
}
