version: '3.8'

services:
  rsshub:
    image: diygod/rsshub:chromium-bundled
    container_name: rsshub_service
    restart: always
    ports:
      - "1200:1200"
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis_cache:6379/'
      CACHE_EXPIRE: 7200                       # Cache responses for 2 hours (limits outgoing hits)
    depends_on:
      - redis_cache

  redis_cache:
    image: redis:alpine
    container_name: rsshub_redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
